# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'D:\a\1\s\SharpHound3\bin\Release\SharpHound.exe'
    ArtifactName: 'SharpHound.exe'
    publishLocation: 'Container'
    
- task: AzureFileCopy@3
  name: UploadFile
  inputs:
    SourcePath: 'D:\a\1\s\SharpHound3\bin\Release\SharpHound.exe'
    azureSubscription: $(SubName)
    Destination: 'AzureBlob'
    storage: $(StorageAccount)
    ContainerName: $(ContainerName)
